.386
WRITE	MACRO A				;9号DOS调用
		LEA DX,A
		MOV AH,9
		INT 21H
		ENDM
STACK   SEGMENT    USE16   STACK
        DB 200  DUP(0)
STACK   ENDS

DATA  SEGMENT USE16
BUF   DB 0AH,0DH,'Please input the number(0-9):$'
BUF2  DB 5 DUP(0)
CLR   DB 0AH,0DH,'$'
DATA  ENDS

CODE    SEGMENT    USE16
        ASSUME CS: CODE, DS: DATA, SS: STACK
START: 
		MOV AX,DATA
		MOV DS,AX
		WRITE BUF
		MOV AH,1
		INT 21H
		CMP AL,'q'
		JE  EXIT
		WRITE CLR  
		
		SUB AL,30H      
		OUT 70H,AL      ;设定将要访问的单元
		IN  AL,71H      ;读取信息
		MOV BL,AL
		AND AL,0FH      ;取低位
		SHR BL,4        ;取高位
		MOVZX BX,BL
		IMUL BX,10
		MOVZX AX,AL
		ADD AX,BX
		LEA SI,BUF2
		MOV BL,16
		DIV BL
		CMP AL,10
		JB LL1
		ADD AL,7
LL1: 	ADD AL,30H
		MOV [SI],AL
		INC SI
		CMP AH,10
		JB LL2
		ADD AH,7
LL2:	ADD AH,30H
		MOV [SI],AH
		INC SI
		MOV BYTE PTR [SI],'H'
		INC SI
		MOV BYTE PTR [SI],'$'
		WRITE BUF2
		JMP START

EXIT:	MOV AH,4CH
		INT 21H
CODE 	ENDS
		END START
